version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=https://grafana.homelab.vladonof.dev/
    ports:
      - 83:3000
    depends_on:
      - prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 84:8080
    restart: unless-stopped

  smokeping:
    image: lscr.io/linuxserver/smokeping:latest
    container_name: smokeping
    hostname: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /var/lib/docker/volumes/smokeping/config:/config
      - /var/lib/docker/volumes/smokeping/data:/data
    ports:
      - 87:80
    restart: unless-stopped

  # homepage:
  #   image: ghcr.io/gethomepage/homepage:latest
  #   container_name: homepage
  #   environment:
  #     HOMEPAGE_ALLOWED_HOSTS: '*'
  #     PUID: 1000 # optional, your user id
  #     PGID: 1000 # optional, your group id
  #   ports:
  #     - 88:3000
  #   volumes:
  #     - /var/lib/docker/volumes/homepage/config:/app/config
  #     - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
  #   restart: unless-stopped

  myspeed:
    image: germannewsmaker/myspeed:latest
    container_name: myspeed
    ports:
      - "79:5216"
    volumes:
      - /var/lib/docker/volumes/myspeed_data:/myspeed/data
    restart: unless-stopped